version: '3.2'     # version: '3.2' also will works

networks:
    swarm_network:
        driver: overlay


services:
    page1:
        image: maranatha/page1:v1

        deploy:
            mode: replicated
            replicas: 1
            placement:
                constraints:
                    - node.hostname == npi3

        ports:
            - published: 81
              target: 81
              mode: host
        environment:
            - NAME=WiFiUS
        networks:
            swarm_network:

    page2:
        image: maranatha/page2:v1

        deploy:
            mode: replicated
            replicas: 1
            placement:
                constraints:
                    - node.hostname == npi1

        ports:
            - published: 5000
              target: 5000
              mode: host
        environment:
            - NAME=NAP

        networks:
            swarm_network:

    visualizer:
        image: alexellis2/visualizer-arm:latest
        ports:
            - "8080:8080"
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
        deploy:
            placement:
                constraints:
                    - node.role == manager
        networks:
            swarm_network:
